### ISSUE TITLE
Shorter name instead of `nanoajax.ajax`? 

### ISSUE THREAD

**Issue by samayo** [yanatan16/nanoajax#17]
Hi, I've been using this library for a month now, and I like it as it does what I want. But, I was wandering why the name has to be long `nanoajax.ajax` is 13 characters. Why not just shorten it, or create an alias like `nano` or `nano.ajax` ... sure it's trivial but I can't get past it everytime I have to write `nanoajax.ajax` .. otherwise :+1:

**Comment by voxpelli** [comment]
You can always rename it to whatever you want by doing something like:

``` javascript
var shortajax = nanoajax.ajax.bind(nanoajax);
```

And if you're using browserify, then you can name the library whatever you want when importing it:

``` javascript
var nano = require('nanoajax');
```

A global package name should be rather unique to avoid collisions + be descriptive about itself and `nanoajax` achieves both + is used in production code so changing it would probably not be such a good idea.

Another similar idea though would be to expose the `nanoajax.ajax()` method on the top module so that it is enough to just do `nanoajax()`. Then it would be easier to rename as well as shorter to access from the start. The change would be as simple as to change the `exports.ajax = ...` to:

```
module.exports = ...;
module.exports.ajax = module.exports;
```

Then both old API and new shorthand would work.

**Comment by yanatan16** [comment]
I don't think I'll shorten the name. Making the export a function is a possibility. I agree with @voxpelli that renaming the object is the best thing to do. Making it shorter might save you a few bytes, but using nanoajax in the first place has saved you hundreds of bytes. It evens out :shipit:
