### ISSUE TITLE
Handle server errors (onerror event)

### ISSUE THREAD

**Issue by finom** [yanatan16/nanoajax#7]
Subj

**Comment by yanatan16** [comment]
Good point. I'm thinking we can possibly use `onload` and `onerror` instead of `onreadystatechange`. I'll look into it.

**update**: I believe `onerror` and `onload` are new in the spec and aren't supported all the way back in IE as this library is meant to support. We might do a better job of testing on `onreadystatechange` as jquery does in https://github.com/jquery/jquery/blob/1.11-stable/src/ajax/xhr.js

**Comment by yanatan16** [comment]
#11 uses `onerror` and `ontimeout` and `onabort`, and allows use of `onprogress`. See version `v0.4.0`
